"use client"

import { Pie, PieChart, Cell, ResponsiveContainer } from "recharts"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  ArrowUp01Icon,
  User03Icon,
} from "@hugeicons/core-free-icons"

import { Card } from "@/components/ui/card"

const KPI_ROWS = [
  "User Engagement Rate",
  "Conversion Rate",
  "Retention & Churn Rate",
  "Revenue Per User (ARPU)",
  "Click-Through Rate (CTR)",
  "Time Spent in App / Website",
] as const

const PEOPLE = 10
const PEOPLE_LIT = 7

const PIE_DATA = [
  { name: "personalize", value: 78, fill: "var(--chart-1)" },
  { name: "rest", value: 22, fill: "var(--muted-foreground)" },
]

export function PersonalizationDashboard() {
  return (
    <Card className="overflow-hidden bg-foreground p-0 text-background">
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_280px]">
        {/* Left: stats grid */}
        <div className="grid divide-y divide-background/15 border-background/15 lg:divide-y-0 lg:divide-x">
          {/* Top: 71% strip */}
          <div className="p-6 md:p-8">
            <div className="flex flex-wrap items-baseline gap-4">
              <p className="cn-font-heading text-6xl font-bold tracking-tight md:text-7xl">
                <span style={{ color: "var(--chart-1)" }}>71</span>
                <span className="text-3xl align-top">%</span>
              </p>
              <p className="max-w-[260px] text-xs leading-relaxed text-background/75">
                of US consumers now expect to receive personalized interactions
              </p>
            </div>
            <div className="mt-5 flex items-end gap-2">
              {Array.from({ length: PEOPLE }).map((_, i) => {
                const lit = i < PEOPLE_LIT
                return (
                  <HugeiconsIcon
                    key={i}
                    icon={User03Icon}
                    className="h-12 w-7"
                    style={{
                      color: lit
                        ? "var(--chart-1)"
                        : "color-mix(in oklch, var(--background) 35%, transparent)",
                    }}
                    strokeWidth={1.5}
                  />
                )
              })}
            </div>
          </div>

          {/* Bottom row: pie + phones */}
          <div className="grid grid-cols-1 divide-y divide-background/15 sm:grid-cols-2 sm:divide-x sm:divide-y-0">
            <div className="flex flex-col gap-3 p-6 md:p-8">
              <div className="flex items-center gap-3">
                <div className="size-20">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={PIE_DATA}
                        dataKey="value"
                        nameKey="name"
                        innerRadius={0}
                        outerRadius={40}
                        startAngle={90}
                        endAngle={-270}
                        stroke="none"
                      >
                        {PIE_DATA.map((d, i) => (
                          <Cell key={i} fill={d.fill} />
                        ))}
                      </Pie>
                    </PieChart>
                  </ResponsiveContainer>
                </div>
                <p className="cn-font-heading text-5xl font-bold tracking-tight">
                  <span style={{ color: "var(--chart-1)" }}>78</span>
                  <span className="text-2xl align-top">%</span>
                </p>
              </div>
              <p className="text-xs leading-relaxed text-background/75">
                of US consumers are more likely to recommend a brand that offers
                personalization to friends and family.
              </p>
            </div>

            <div className="flex flex-col gap-3 p-6 md:p-8">
              <div className="flex items-center gap-3">
                <p className="cn-font-heading text-5xl font-bold tracking-tight">
                  <span className="text-background">40</span>
                  <span className="text-2xl align-top">%</span>
                </p>
                <PhonesIcon />
              </div>
              <p className="text-xs leading-relaxed text-background/75">
                more revenue is generated by companies that effectively leverage
                personalized marketing actions or tactics.
              </p>
            </div>
          </div>
        </div>

        {/* Right: KPI rail */}
        <div className="flex flex-col divide-y divide-background/15 border-background/15 lg:border-l">
          {KPI_ROWS.map((label) => (
            <div key={label} className="flex items-center gap-3 px-5 py-4">
              <span
                className="grid size-9 place-items-center rounded-full"
                style={{
                  background: "color-mix(in oklch, var(--background) 12%, transparent)",
                  color: "var(--chart-1)",
                }}
              >
                <HugeiconsIcon icon={ArrowUp01Icon} className="size-4" strokeWidth={2.5} />
              </span>
              <span className="text-xs text-background/85">{label}</span>
            </div>
          ))}
        </div>
      </div>
    </Card>
  )
}

function PhonesIcon() {
  return (
    <svg viewBox="0 0 80 60" className="h-14 w-20" aria-hidden>
      <rect
        x="40"
        y="6"
        width="26"
        height="48"
        rx="4"
        fill="color-mix(in oklch, var(--background) 35%, transparent)"
      />
      <rect
        x="14"
        y="2"
        width="26"
        height="52"
        rx="4"
        fill="var(--chart-1)"
      />
      <rect
        x="22"
        y="9"
        width="10"
        height="2"
        rx="1"
        fill="color-mix(in oklch, var(--foreground) 30%, transparent)"
      />
    </svg>
  )
}
